# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-23 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
